### ISSUE TITLE
correcciones

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-rutatlantica#1]
les hice un commit con algunos arreglos, de cosas que dijimos en clase el otro dia.

tienen un problema con la colisiones, que no estan bien planteadas. usen el whenCollide, sin comparar manualmente las posiciones

lo que comente en clase, que no hagan tanto copy paste, sino que modelen los bordes del laberinto con alguna abstraccion, tipo fila, columna, camino, etc.

les habia pedido de hacer algun feature mas, por ejemplo con el manejo del tiempo o niveles.
@MatiasDelorenzi @lucasreinaud @FaustoRugiero

**Comment by FaustoRugiero** [comment]
Se solucionaron todas esas cosas, el unico problema que hay ahora es que al ejecutar el juego, se cierra inmediatamente. No logramos encontrar que es lo que da ese problema (Branch de correcciones).
